let PACK,BOOKS,CAPACITY,state;
const byId=id=>BOOKS.find(b=>b.id===id);
function loadPack(id){PACK=COZY_PACKS[id];BOOKS=PACK.books;CAPACITY=PACK.shelf.capacity;document.documentElement.style.setProperty("--shelf-columns",PACK.shelf.columns);document.documentElement.style.setProperty("--slot-height",PACK.shelf.slotHeight+"px");document.documentElement.style.setProperty("--spine",PACK.bookStyle.spine);document.documentElement.style.setProperty("--spine-text",PACK.bookStyle.text);document.documentElement.style.setProperty("--offer",PACK.bookStyle.offer);document.getElementById("window").style.height=PACK.view.height+"px";resetWorld()}
function resetWorld(){state={shelf:[],offers:[],pool:BOOKS.map(b=>b.id),facts:new Set()};fillOffers();render()}
function draw(){const choices=state.pool.filter(id=>!state.offers.includes(id)&&!state.shelf.includes(id));return choices.length?choices[Math.floor(Math.random()*choices.length)]:null}
function fillOffers(){while(state.offers.length<3){const id=draw();if(!id)break;state.offers.push(id)}}
function choose(id){if(state.shelf.length>=CAPACITY)return;const rejected=state.offers.filter(x=>x!==id);state.shelf.push(id);byId(id).facts.forEach(f=>state.facts.add(f));state.pool=state.pool.filter(x=>x!==id);const linger=rejected[Math.floor(Math.random()*rejected.length)];state.offers=linger?[linger]:[];fillOffers();render();showBook(byId(id))}
function showBook(b){document.getElementById("dialog-content").innerHTML=`<h2>${b.title}</h2><p>${b.text}</p>`;document.getElementById("book-dialog").showModal()}
function render(){document.getElementById("progress").textContent=`${state.shelf.length}/${CAPACITY}`;document.getElementById("shelf").innerHTML=Array.from({length:CAPACITY},(_,i)=>state.shelf[i]?`<div class="book spine" title="${byId(state.shelf[i]).title}">${byId(state.shelf[i]).title}</div>`:`<div class="slot"></div>`).join("");document.getElementById("offers").innerHTML=state.offers.map(id=>{const b=byId(id);return `<button class="offer" data-id="${id}"><span>Available volume</span><strong>${b.title}</strong><em>Add to library</em></button>`}).join("");document.querySelectorAll(".offer").forEach(el=>el.onclick=()=>choose(el.dataset.id));renderWorld()}
function renderWorld(){const f=state.facts,bits=[];for(const o of PACK.worldObjects){if(!f.has(o.fact))continue;let content=o.content;for(const v of o.variants||[])if(f.has(v.requires))content=v.content;bits.push(`<div class="${o.className}">${content}</div>`)}document.getElementById("world").innerHTML=bits.join("");document.querySelector(".haze").textContent=PACK.view.haze;document.querySelector(".haze").style.opacity=Math.max(.05,1-state.shelf.length/CAPACITY);const n=PACK.view.notes;document.getElementById("world-note").textContent=state.shelf.length===CAPACITY?n[4]:state.shelf.length<1?n[0]:state.shelf.length<3?n[1]:state.shelf.length<8?n[2]:n[3]}
document.getElementById("close-dialog").onclick=()=>document.getElementById("book-dialog").close();document.getElementById("reset").onclick=resetWorld;loadPack("starter");