let CONFIG,BOOKS,CAPACITY,state;const byId=id=>BOOKS.find(b=>b.id===id);
function selected(cls){return[...document.querySelectorAll(cls+" input:checked")].map(x=>x.value)}
function setChecks(cls,ids){document.querySelectorAll(cls+" input").forEach(x=>x.checked=ids.includes(x.value))}
function applyBundle(id){const b=COZY_ASSETS.bundles[id];setChecks(".book-set-options",b.bookSets);setChecks(".world-set-options",b.worldSets)}
function startGame(){const bookIds=selected(".book-set-options"),worldIds=selected(".world-set-options");if(!bookIds.length){document.getElementById("setup-error").textContent="Choose at least one book set.";return}const missing=[...new Set(bookIds.flatMap(id=>COZY_ASSETS.bookSets[id].requiresWorldSets||[]))].filter(id=>!worldIds.includes(id));if(missing.length){document.getElementById("setup-error").textContent="Missing required world objects: "+missing.map(id=>COZY_ASSETS.worldSets[id].name).join(", ")+". Enable them or choose different books.";return}const view=COZY_ASSETS.views.default,shelf=COZY_ASSETS.shelves.default,style=COZY_ASSETS.bookStyles.default;BOOKS=bookIds.flatMap(id=>COZY_ASSETS.bookSets[id].books.map(b=>({...b,id:id+"__"+b.id})));const requested=parseInt(document.getElementById("shelf-capacity").value,10);if(!Number.isInteger(requested)||requested<1){document.getElementById("setup-error").textContent="Bookshelf size must be at least 1.";return}CAPACITY=Math.min(requested,BOOKS.length);CONFIG={view,shelf,style,worldObjects:worldIds.flatMap(id=>COZY_ASSETS.worldSets[id].objects)};document.documentElement.style.setProperty("--shelf-columns",shelf.columns);document.documentElement.style.setProperty("--slot-height",shelf.slotHeight+"px");document.documentElement.style.setProperty("--spine",style.spine);document.documentElement.style.setProperty("--spine-text",style.text);document.documentElement.style.setProperty("--offer",style.offer);document.getElementById("window").style.height=view.height+"px";document.getElementById("pack-label").textContent=bookIds.map(id=>COZY_ASSETS.bookSets[id].name).join(" + ")+" · "+CAPACITY+" shelf slots";document.getElementById("setup-error").textContent="";document.getElementById("setup").hidden=true;document.getElementById("game").hidden=false;resetWorld()}
function returnToSetup(){document.getElementById("book-dialog").close();document.getElementById("game").hidden=true;document.getElementById("setup").hidden=false}
function resetWorld(){state={shelf:[],offers:[],pool:BOOKS.map(b=>b.id),facts:new Set()};fillOffers();render()}
function draw(){const c=state.pool.filter(id=>!state.offers.includes(id)&&!state.shelf.includes(id));return c.length?c[Math.floor(Math.random()*c.length)]:null}
function fillOffers(){while(state.offers.length<3){const id=draw();if(!id)break;state.offers.push(id)}}
function choose(id){if(state.shelf.length>=CAPACITY)return;const rejected=state.offers.filter(x=>x!==id);state.shelf.push(id);byId(id).facts.forEach(f=>state.facts.add(f));state.pool=state.pool.filter(x=>x!==id);const linger=rejected[Math.floor(Math.random()*rejected.length)];state.offers=linger?[linger]:[];fillOffers();render();showBook(byId(id))}
function showBook(b){document.getElementById("dialog-content").innerHTML=`<h2>${b.title}</h2><p>${b.text}</p>`;document.getElementById("book-dialog").showModal()}
function render(){document.getElementById("progress").textContent=`${state.shelf.length}/${CAPACITY}`;document.getElementById("shelf").innerHTML=Array.from({length:CAPACITY},(_,i)=>state.shelf[i]?`<div class="book spine">${byId(state.shelf[i]).title}</div>`:`<div class="slot"></div>`).join("");document.getElementById("offers").innerHTML=state.offers.map(id=>{const b=byId(id);return`<button class="offer" data-id="${id}"><span>Available volume</span><strong>${b.title}</strong><em>Add to library</em></button>`}).join("");document.querySelectorAll(".offer").forEach(el=>el.onclick=()=>choose(el.dataset.id));renderWorld()}
function renderWorld(){const f=state.facts,bits=[];for(const o of CONFIG.worldObjects){if(!f.has(o.fact))continue;let content=o.content;for(const v of o.variants||[])if(f.has(v.requires))content=v.content;bits.push(`<div class="${o.className}">${content}</div>`)}document.getElementById("world").innerHTML=bits.join("");document.querySelector(".haze").textContent=CONFIG.view.haze;document.querySelector(".haze").style.opacity=Math.max(.05,1-state.shelf.length/CAPACITY);const n=CONFIG.view.notes,r=state.shelf.length/CAPACITY;document.getElementById("world-note").textContent=r===1?n[4]:r===0?n[0]:r<.25?n[1]:r<.67?n[2]:n[3]}
document.getElementById("close-dialog").onclick=()=>document.getElementById("book-dialog").close();document.getElementById("start").onclick=startGame;document.getElementById("reselect").onclick=returnToSetup;document.querySelectorAll("[data-bundle]").forEach(b=>b.onclick=()=>applyBundle(b.dataset.bundle));